### ISSUE TITLE
关于缓存模块

### ISSUE THREAD

**Issue by visamz** [typecho/framework#1]
正在更新的 70 大大，我看到你正在更新缓存模块，能否增加 memcached 缓存 和 file 缓存呢？

**Comment by doudoutime** [comment]
看到了redis，其实只要接口设置合理，缓存方式可以自己增加。

**Comment by visamz** [comment]
@qqff01 嗯，那啥也不用写了，啥都可以自己增加的！

**Comment by joyqi** [comment]
memcache会加上的

**Comment by visamz** [comment]
@joyqi 看到 apc 缓存素空的，是不是忘记加了 - -

**Comment by visamz** [comment]
@joyqi 我感觉在框架根目录应该加一个初始化入口文件，以载入一些必须的的 api ，比如 Autoloader,base,server 。
